### ISSUE TITLE
socat not included

### ISSUE THREAD

**Issue by diogobaeder** [dariosky/wfcli#1]
Hi!

Unfortunately, for later versions of acme.sh it requires socat to be installed. I have a package that does this installation (my package relies on yours, actually), and I thought of proposing a merge request with the installation happening to a specific version of socat, but I'm not entirely sure that this is a good idea, so I thought it would be better to just create the ticket here and perhaps trigger some discussion on this first.

This is where I install socat with my package, just as a reference: https://github.com/diogobaeder/diogobaeder.webfaction/blob/master/diogobaeder/webfaction/tools.py#L154 - it's just a personal package, though, I have no intention of worrying about other people using it (if someone else does, I'll create a more decent package for these purposes).

What do you think?

Cheers,
Diogo

**Comment by dariosky** [comment]
Hi Diogo!
I'm happy that you're using it, I'll try it again with the latest acme.sh and will get back to you.
Thanks for reporting it.

**Comment by dariosky** [comment]
I've tried upgrading acme.sh (version 2.7.4), and try to force a renewal of domains, but I didn't find any problem.
I've read the dropped support for nc [here](https://community.letsencrypt.org/t/acme-sh-drops-nc-and-uses-socat-for-standalone-mode/41579).
I think it should still work with the production letsencrypt, are you using the staging servers?

**Comment by diogobaeder** [comment]
Hi Dario! :-)

I'm not sure why you didn't get the error... perhaps you already have socat installed?

I'm not using the staging environment, not. At least, not now.

Thanks!

**Comment by dariosky** [comment]
I don't have socat installed.
I didn't go through the whole process, maybe the error you get is during ownership verification.
Do you have some log that can help reproduce it?

**Comment by diogobaeder** [comment]
Hi Dario,

The log was pretty simple, it just stated that it couldn't run because socat was missing. I can't reproduce it anymore because I got socat installed so that I could have acme working. Here is where socat is checked in acme: https://github.com/Neilpang/acme.sh/search?utf8=%E2%9C%93&q=socat&type=

If you didn't have this issue, and don't have socat installed, then it's probably the case that you're either using some dependency from acme in an older version, or you're using an older version of acme itself.

Cheers!

**Comment by dariosky** [comment]
Time passed, I'm closing the issue. For different acme version I'll add some test suite than runs on the most recent acme.
